Repository Picket-P/Picket-Backend, pull requests merged in 2025-04, with the labels that each got.

#22 인증/인가 API 구현
  docs/AUTH.md
  src/main/java/com/example/picket/common/annotation/Auth.java
  src/main/java/com/example/picket/common/auth/AuthUserArgumentResolver.java
  src/main/java/com/example/picket/common/consts/Const.java
  src/main/java/com/example/picket/common/dto/AuthUser.java
  src/main/java/com/example/picket/common/exception/ErrorCode.java
  src/main/java/com/example/picket/common/exception/GlobalExceptionHandler.java
  src/main/java/com/example/picket/common/interceptor/AuthInterceptor.java
  src/main/java/com/example/picket/config/WebConfig.java
  src/main/java/com/example/picket/domain/auth/controller/AuthController.java
  src/main/java/com/example/picket/domain/auth/dto/request/SigninRequest.java
  src/main/java/com/example/picket/domain/auth/dto/request/SignupRequest.java
  src/main/java/com/example/picket/domain/auth/dto/response/SigninResponse.java
  src/main/java/com/example/picket/domain/auth/service/AuthService.java
  src/main/java/com/example/picket/domain/user/repository/UserRepository.java
Labels: enhancement, Approved

#26 인증/인가 ErrorCode 수정
  src/main/java/com/example/picket/common/auth/AuthUserArgumentResolver.java
  src/main/java/com/example/picket/common/enums/Category.java
  src/main/java/com/example/picket/common/enums/Gender.java
  src/main/java/com/example/picket/common/enums/Grade.java
  src/main/java/com/example/picket/common/enums/TicketStatus.java
  src/main/java/com/example/picket/common/enums/UserRole.java
  src/main/java/com/example/picket/common/exception/ErrorCode.java
  src/main/java/com/example/picket/common/interceptor/AuthInterceptor.java
  src/main/java/com/example/picket/domain/auth/service/AuthService.java
Labels: enhancement, Need Reviews

#40 인증/인가 API 인터셉터 관련 수정
  src/main/java/com/example/picket/common/consts/Const.java
  src/main/java/com/example/picket/common/interceptor/AuthInterceptor.java
  src/main/java/com/example/picket/config/WebConfig.java
Labels: enhancement, Approved

#43 Ticket : 티켓 단건 조회 API 수정
  src/main/java/com/example/picket/common/exception/ErrorCode.java
  src/main/java/com/example/picket/domain/ticket/controller/TicketController.java
  src/main/java/com/example/picket/domain/ticket/service/TicketQueryService.java
Labels: Approved, refactor

#55 인증/인가 테스트 코드 작성
  src/test/java/com/example/picket/domain/auth/service/AuthServiceTest.java
Labels: Approved, test

#56 좋아요 테스트 코드 작성
  docs/LIKE.md
  src/test/java/com/example/picket/domain/like/service/LikeCommandServiceTest.java
  src/test/java/com/example/picket/domain/like/service/LikeQueryServiceTest.java
Labels: Approved, test

#62 Swagger 설정 추가 및 댓글 API 문서화 어노테이션 적용
  build.gradle
  src/main/java/com/example/picket/common/annotation/Auth.java
  src/main/java/com/example/picket/common/annotation/AuthPermission.java
  src/main/java/com/example/picket/common/consts/Const.java
  src/main/java/com/example/picket/config/SwaggerConfig.java
  src/main/java/com/example/picket/domain/comment/controller/CommentController.java
  src/main/java/com/example/picket/domain/comment/dto/request/CommentRequest.java
  src/main/resources/application.yml
Labels: feat, Need Reviews

#71 티켓 Swagger + 티켓 생성 권한 제한 리팩토링
  src/main/java/com/example/picket/common/aop/TicketServiceAspect.java
  src/main/java/com/example/picket/domain/ticket/controller/TicketController.java
Labels: Approved, refactor

#69 인증/인가 Swagger 적용
  src/main/java/com/example/picket/domain/auth/controller/AuthController.java
  src/main/java/com/example/picket/domain/auth/dto/request/SigninRequest.java
  src/main/java/com/example/picket/domain/auth/dto/request/SignupRequest.java
Labels: feat, Approved

#70 좋아요 Swagger 적용
  src/main/java/com/example/picket/domain/like/controller/LikeController.java
Labels: feat, Approved

#77 티켓 생성 기능 수정
  src/main/java/com/example/picket/domain/show/entity/ShowDate.java
  src/main/java/com/example/picket/domain/ticket/service/TicketCommandService.java
  src/test/java/com/example/picket/domain/ticket/service/TicketCommandServiceTest.java
Labels: Approved, fix

#82 인증/인가 추가 구현 및 좋아요, 티켓 부분 PageResponse 통일 수정
  src/main/java/com/example/picket/common/auth/AuthUserArgumentResolver.java
  src/main/java/com/example/picket/common/interceptor/AuthInterceptor.java
  src/main/java/com/example/picket/domain/auth/controller/AuthController.java
  src/main/java/com/example/picket/domain/auth/service/AuthService.java
  src/main/java/com/example/picket/domain/like/controller/LikeController.java
  src/main/java/com/example/picket/domain/show/dto/request/ShowCreateRequest.java
  src/main/java/com/example/picket/domain/show/dto/request/ShowUpdateRequest.java
  src/main/java/com/example/picket/domain/ticket/controller/TicketController.java
Labels: Approved, refactor

#83 chore: springdoc 2.8.6 업그레이드에 따른 불필요 설정 제거
  build.gradle
  src/main/java/com/example/picket/domain/show/dto/request/ShowCreateRequest.java
  src/main/java/com/example/picket/domain/show/dto/request/ShowUpdateRequest.java
  src/main/resources/application.yml
Labels: Approved, fix

#85 AuthServiceTest 에러 수정
  src/test/java/com/example/picket/domain/auth/service/AuthServiceTest.java
Labels: Approved, fix, test

#128 S3/Image : BaseEntity 사용한 최적화 리팩토링
  build.gradle
  src/main/java/com/example/picket/common/scheduler/ImageRemoveScheduler.java
  src/main/java/com/example/picket/common/service/S3Service.java
  src/main/java/com/example/picket/domain/images/repository/ShowImageRepository.java
  src/main/java/com/example/picket/domain/images/repository/UserImageRepository.java
  src/main/java/com/example/picket/domain/show/controller/ShowController.java
  src/main/java/com/example/picket/domain/show/service/ShowCommandService.java
  src/main/java/com/example/picket/domain/user/controller/UserController.java
  src/main/java/com/example/picket/domain/user/service/UserCommandService.java
  src/test/java/com/example/picket/common/service/S3ServiceTest.java
  src/test/java/com/example/picket/domain/show/service/ShowCommandServiceTest.java
  src/test/java/com/example/picket/domain/user/service/UserCommandServiceTest.java
Labels: Approved, refactor

#135 Payment : 화면 렌더링 시 orderId 보여주도록 수정
  src/main/resources/static/checkout.html
Labels: Approved, fix
